import jsPDF from 'jspdf'

export interface EstimateData {
  id: string
  clientName: string
  clientPhone: string
  clientEmail: string
  address: string
  zipCode: string
  projectType: string
  createdAt: Date
  lineItems: Array<{
    description: string
    quantity: number
    unit: string
    notes?: string | null
    laborCost: number
    materialCost: number
    permitCost: number
    disposalCost: number
    subtotal: number
  }>
  totalAmount: number
}

export function generatePDF(estimate: EstimateData): void {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 20
  let yPos = margin

  // Header
  doc.setFontSize(24)
  doc.setTextColor(14, 165, 233) // primary-500
  doc.text('RenoRate', margin, yPos)
  
  yPos += 10
  doc.setFontSize(12)
  doc.setTextColor(0, 0, 0)
  doc.text('See the Rate Before You Renovate.', margin, yPos)
  
  yPos += 15
  doc.setDrawColor(200, 200, 200)
  doc.line(margin, yPos, pageWidth - margin, yPos)
  yPos += 10

  // Estimate Info
  doc.setFontSize(16)
  doc.setFont(undefined, 'bold')
  doc.text('Estimate Details', margin, yPos)
  yPos += 10

  doc.setFontSize(10)
  doc.setFont(undefined, 'normal')
  doc.text(`Client: ${estimate.clientName}`, margin, yPos)
  yPos += 6
  doc.text(`Phone: ${estimate.clientPhone}`, margin, yPos)
  yPos += 6
  doc.text(`Email: ${estimate.clientEmail}`, margin, yPos)
  yPos += 6
  doc.text(`Address: ${estimate.address}, ${estimate.zipCode}`, margin, yPos)
  yPos += 6
  doc.text(`Project Type: ${estimate.projectType}`, margin, yPos)
  yPos += 6
  doc.text(`Date: ${new Date(estimate.createdAt).toLocaleDateString()}`, margin, yPos)
  yPos += 10

  // Line Items Table Header
  doc.setFont(undefined, 'bold')
  doc.setFontSize(10)
  doc.text('Description', margin, yPos)
  doc.text('Qty', margin + 60, yPos)
  doc.text('Unit', margin + 80, yPos)
  doc.text('Labor', margin + 110, yPos)
  doc.text('Materials', margin + 140, yPos)
  doc.text('Permits', margin + 170, yPos)
  doc.text('Disposal', margin + 195, yPos)
  doc.text('Subtotal', margin + 220, yPos)
  yPos += 5
  doc.setDrawColor(200, 200, 200)
  doc.line(margin, yPos, pageWidth - margin, yPos)
  yPos += 8

  // Line Items
  doc.setFont(undefined, 'normal')
  doc.setFontSize(9)
  estimate.lineItems.forEach((item) => {
    if (yPos > 250) {
      doc.addPage()
      yPos = margin
    }

    doc.text(item.description.substring(0, 25), margin, yPos)
    doc.text(item.quantity.toString(), margin + 60, yPos)
    doc.text(item.unit, margin + 80, yPos)
    doc.text(`$${item.laborCost.toFixed(2)}`, margin + 110, yPos)
    doc.text(`$${item.materialCost.toFixed(2)}`, margin + 140, yPos)
    doc.text(`$${item.permitCost.toFixed(2)}`, margin + 170, yPos)
    doc.text(`$${item.disposalCost.toFixed(2)}`, margin + 195, yPos)
    doc.text(`$${item.subtotal.toFixed(2)}`, margin + 220, yPos)
    yPos += 6

    if (item.notes) {
      doc.setFontSize(8)
      doc.setTextColor(100, 100, 100)
      doc.text(`  Note: ${item.notes}`, margin + 5, yPos)
      yPos += 5
      doc.setFontSize(9)
      doc.setTextColor(0, 0, 0)
    }
  })

  yPos += 5
  doc.setDrawColor(200, 200, 200)
  doc.line(margin, yPos, pageWidth - margin, yPos)
  yPos += 10

  // Total
  doc.setFont(undefined, 'bold')
  doc.setFontSize(14)
  doc.text(`Total Estimate: $${estimate.totalAmount.toFixed(2)}`, margin, yPos)

  // Footer
  yPos = doc.internal.pageSize.getHeight() - 20
  doc.setFont(undefined, 'normal')
  doc.setFontSize(8)
  doc.setTextColor(100, 100, 100)
  doc.text('Generated by RenoRate', margin, yPos)
  doc.text(`Estimate ID: ${estimate.id}`, pageWidth - margin - 50, yPos, { align: 'right' })

  // Save PDF
  doc.save(`RenoRate-Estimate-${estimate.id.substring(0, 8)}.pdf`)
}
